# Generated by Django 3.2 on 2021-10-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_rename_softwarerequestmodel_software_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='licenses_list',
            fields=[
                ('id_license', models.AutoField(primary_key=True, serialize=False)),
                ('license_name', models.CharField(max_length=40)),
                ('license_type', models.CharField(max_length=40)),
                ('license_stock', models.PositiveSmallIntegerField()),
                ('license_in_use', models.PositiveSmallIntegerField()),
                ('license_due_date', models.DateField()),
            ],
        ),
    ]
