# Generated by Django 3.2 on 2021-10-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_licenses_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='LicensesList',
            options={'verbose_name': 'license', 'verbose_name_plural': 'licenses'},
        ),
    ]
