# Generated by Django 3.2 on 2021-10-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_software_form_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='SoftwareForm',
            name='software_type',
            field=models.IntegerField(choices=[(1, 'Gratis'), (2, 'Pagada'), (3, 'Subscripción')], default=1),
        ),
    ]
