# Generated by Django 3.2 on 2021-12-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_auto_20211111_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typelicense',
            options={'verbose_name': 'Tipo de licencia', 'verbose_name_plural': 'Tipo de licencia'},
        ),
        migrations.RemoveField(
            model_name='licenseslist',
            name='license_in_use',
        ),
        migrations.AlterField(
            model_name='typelicense',
            name='type_name',
            field=models.TextField(default=''),
        ),
    ]
