# Generated by Django 3.2 on 2021-12-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_auto_20211204_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareform',
            name='software_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenses.typelicense'),
        ),
    ]
