# Generated by Django 3.2 on 2021-12-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211202_1732'),
        ('licenses', '0009_alter_softwareform_software_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareform',
            name='room_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
        migrations.AlterField(
            model_name='softwareform',
            name='status',
            field=models.IntegerField(choices=[(1, 'No realizada'), (2, 'Realizada')], default=2),
        ),
    ]
