# Generated by Django 3.2 on 2022-01-08 18:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0011_auto_20220108_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseslist',
            name='license_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=3000)),
        ),
    ]
