# Generated by Django 3.2 on 2022-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0012_alter_licenseslist_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseslist',
            name='creation_date',
            field=models.DateField(auto_now=True, verbose_name='Creation date'),
        ),
    ]
