# Generated by Django 3.2 on 2022-02-27 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='inactive_by',
            new_name='deleted_by',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='inactive_by',
            new_name='deleted_by',
        ),
        migrations.RenameField(
            model_name='workstation',
            old_name='inactive_by',
            new_name='deleted_by',
        ),
        migrations.AddField(
            model_name='campus',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workstation',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
