# Generated by Django 3.2 on 2021-12-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211107_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='inactive_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
