# Generated by Django 3.2.4 on 2021-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_report_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reason',
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('HW', 'Hardware'), ('SO', 'Sistema Operativo'), ('SW', 'Software')], default='', max_length=2),
        ),
    ]
