# Generated by Django 3.2.4 on 2021-09-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20210904_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['date_created']},
        ),
    ]
