# Generated by Django 3.2.4 on 2021-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='cpu',
            field=models.CharField(choices=[('P', 'Presenta'), ('NP', 'No Presenta'), ('D', 'Dañado')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='revision',
            name='keyboard',
            field=models.CharField(choices=[('P', 'Presenta'), ('NP', 'No Presenta'), ('D', 'Dañado')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='revision',
            name='monitor',
            field=models.CharField(choices=[('P', 'Presenta'), ('NP', 'No Presenta'), ('D', 'Dañado')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='revision',
            name='mouse',
            field=models.CharField(choices=[('P', 'Presenta'), ('NP', 'No Presenta'), ('D', 'Dañado')], default='', max_length=2),
        ),
    ]
