# Generated by Django 3.2.4 on 2021-10-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_alter_report_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Externuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.externuser'),
        ),
    ]
