# Generated by Django 3.2.4 on 2021-11-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_room_options'),
        ('monitoring', '0023_alter_externuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc_Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, choices=[(1, 'Monitor'), (2, 'Mouse'), (3, 'Teclado'), (4, 'CPU'), (5, 'Software'), (6, 'Sistema Operativo')], null=True)),
                ('descriptoin', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workstation')),
            ],
        ),
    ]
