# Generated by Django 3.2.4 on 2021-11-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_room_options'),
        ('monitoring', '0028_alter_scheduledreview_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreview',
            name='date_scheduled',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledreview',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
    ]
