# Generated by Django 3.2.4 on 2021-11-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0031_alter_scheduledreview_date_scheduled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledreview',
            options={'ordering': ['-id']},
        ),
    ]
