# Generated by Django 3.2.4 on 2021-10-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210914_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['name']},
        ),
    ]
