# Generated by Django 3.2.4 on 2021-11-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workstation',
            options={},
        ),
    ]
