# Generated by Django 3.2.4 on 2021-12-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreport',
            name='state',
            field=models.CharField(blank=True, choices=[('A', 'Abierto'), ('R', 'Revisando'), ('C', 'Cerrado')], default='A', max_length=1, null=True),
        ),
    ]
