# Generated by Django 3.2.4 on 2022-01-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_revision_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='state',
        ),
    ]
