# Generated by Django 3.2.4 on 2021-08-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20210826_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Software'), (2, 'Hardware')], null=True),
        ),
    ]
