# Generated by Django 3.2.4 on 2021-08-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20210826_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('H', 'Hardware'), ('S', 'Software')], default='', max_length=20),
        ),
    ]
