# Generated by Django 3.2.4 on 2021-09-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date_created']},
        ),
    ]
