# Generated by Django 3.2.4 on 2021-09-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_alter_report_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor', models.CharField(choices=[('P', 'Presenta'), ('NP', 'Presenta'), ('D', 'Dañado')], default='', max_length=2)),
                ('mouse', models.CharField(choices=[('P', 'Presenta'), ('NP', 'Presenta'), ('D', 'Dañado')], default='', max_length=2)),
                ('keyboard', models.CharField(choices=[('P', 'Presenta'), ('NP', 'Presenta'), ('D', 'Dañado')], default='', max_length=2)),
                ('cpu', models.CharField(choices=[('P', 'Presenta'), ('NP', 'Presenta'), ('D', 'Dañado')], default='', max_length=2)),
                ('SO', models.CharField(choices=[('O', 'Operativo'), ('F', 'Falla'), ('N', 'No Tiene')], default='', max_length=2)),
                ('software', models.CharField(choices=[('O', 'Operativo'), ('F', 'Falla'), ('N', 'No Tiene')], default='', max_length=2)),
                ('observation', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.pc')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.lab')),
            ],
        ),
    ]
