# Generated by Django 3.2.4 on 2021-10-05 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210622_0517'),
        ('core', '0002_auto_20210914_0159'),
        ('monitoring', '0017_alter_report_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='room',
        ),
        migrations.AddField(
            model_name='revision',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workstation'),
        ),
        migrations.CreateModel(
            name='ScheduledReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scheduled', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room')),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='scheduled_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.scheduledreview'),
        ),
    ]
