# Generated by Django 3.2.4 on 2021-10-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210914_0159'),
        ('monitoring', '0018_auto_20211005_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extern_User',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='room',
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workstation'),
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='Pc',
        ),
    ]
