# Generated by Django 3.2.4 on 2021-10-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_alter_revision_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-id']},
        ),
    ]
