# Generated by Django 3.2.4 on 2021-11-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_pc_maintenance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pc_Maintenance',
        ),
    ]
