# Generated by Django 3.2.4 on 2021-11-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_room_options'),
        ('monitoring', '0026_auto_20211105_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreview',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
    ]
