# Generated by Django 3.2.4 on 2021-11-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_alter_scheduledreview_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreview',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
