# Generated by Django 3.2.4 on 2021-11-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0029_auto_20211105_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreview',
            name='date_scheduled',
            field=models.DateField(),
        ),
    ]
