# Generated by Django 3.2.4 on 2021-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_alter_scheduledreview_date_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreview',
            name='date_scheduled',
            field=models.DateTimeField(),
        ),
    ]
