# Generated by Django 3.2.4 on 2021-12-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0034_auto_20211204_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreport',
            name='state',
            field=models.CharField(blank=True, choices=[('A', 'Abierto'), ('C', 'Cerrado')], default='A', max_length=1, null=True),
        ),
    ]
