# Generated by Django 3.2 on 2023-03-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(blank=True, max_length=50, null=True)),
                ('pc', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
