# Generated by Django 3.2 on 2023-03-16 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('activity', '0002_auto_20230316_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='lab',
        ),
        migrations.AlterField(
            model_name='session',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workstation'),
        ),
    ]
