# Generated by Django 3.2 on 2023-03-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('activity', '0003_auto_20230316_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='pc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workstation'),
        ),
    ]
