# Generated by Django 3.2 on 2023-03-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('activity', '0004_alter_session_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='alive',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('pc', 'start')},
        ),
    ]
