# Generated by Django 3.2 on 2023-05-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('activity', '0005_auto_20230319_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='pc',
            new_name='workstation',
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('workstation', 'start')},
        ),
    ]
