# Generated by Django 3.2 on 2021-06-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='since',
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='Role', max_length=50),
        ),
    ]
