# Generated by Django 3.2 on 2021-11-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20210914_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_petition', models.CharField(default='', max_length=50)),
                ('email_petition', models.CharField(default='', max_length=150)),
                ('nrc_petition', models.CharField(blank=True, default='', max_length=10)),
                ('cant_pc_petition', models.IntegerField(default='')),
                ('day_start_petition', models.DateField(null=True)),
                ('day_finish_petition', models.DateField(null=True)),
                ('memo_petition', models.CharField(default='', max_length=250, null=True)),
                ('status_petition', models.CharField(blank=True, choices=[('P', 'Pendiente'), ('A', 'Aceptado'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('campus_petition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campus')),
                ('laboratory_petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='modulepetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_module', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miercoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sabado'), ('DOM', 'Domingo')], max_length=50)),
                ('start_module', models.CharField(choices=[('1D', '08:30-09:15'), ('2D', '09:25-10:10'), ('3D', '10:20-11:05'), ('4D', '11:15-12:00'), ('5D', '12:10-12:55'), ('6D', '13:05-13:50'), ('7D', '14:00-14:45'), ('8D', '14:55-15:40'), ('9D', '15:50-16:35'), ('10D', '16:45-17:30'), ('11D', '17:40-18:25'), ('12D', '18:35-19:20'), ('13D', '19:30-20:15'), ('14D', '20:25-18:50'), ('1V', '19:00-19:45'), ('2V', '19:46-20:30'), ('3V', '20:40-21:25'), ('4V', '21:26-22:10'), ('5V', '22:20-23:05'), ('6V', '23:06-23:50'), ('7V', '08:30-17:30')], max_length=50)),
                ('finish_module', models.CharField(choices=[('1D', '08:30-09:15'), ('2D', '09:25-10:10'), ('3D', '10:20-11:05'), ('4D', '11:15-12:00'), ('5D', '12:10-12:55'), ('6D', '13:05-13:50'), ('7D', '14:00-14:45'), ('8D', '14:55-15:40'), ('9D', '15:50-16:35'), ('10D', '16:45-17:30'), ('11D', '17:40-18:25'), ('12D', '18:35-19:20'), ('13D', '19:30-20:15'), ('14D', '20:25-18:50'), ('1V', '19:00-19:45'), ('2V', '19:46-20:30'), ('3V', '20:40-21:25'), ('4V', '21:26-22:10'), ('5V', '22:20-23:05'), ('6V', '23:06-23:50'), ('7V', '08:30-17:30')], max_length=50)),
                ('labpetition_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.labpetition')),
            ],
        ),
    ]
