# Generated by Django 3.2 on 2021-12-19 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_auto_20211202_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=50)),
                ('type_event', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_module', models.CharField(default='', max_length=50)),
                ('name_module', models.CharField(default='', max_length=50)),
                ('start_module', models.TimeField(null=True)),
                ('finish_module', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_petition', models.CharField(default='', max_length=50)),
                ('email_petition', models.CharField(default='', max_length=150)),
                ('nrc_petition', models.CharField(blank=True, default='', max_length=10)),
                ('computer_petition', models.IntegerField(default='')),
                ('date_start_petition', models.DateField(null=True)),
                ('date_finish_petition', models.DateField(null=True)),
                ('day_petition', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado'), ('0', 'Domingo')], default='0', max_length=2)),
                ('time_start_petition', models.TimeField(null=True)),
                ('time_finish_petition', models.TimeField(null=True)),
                ('recurrence', models.CharField(choices=[('01', 'Diario'), ('07', 'Semanal'), ('28', 'Mensual')], default='01', max_length=2)),
                ('memo_petition', models.CharField(default='', max_length=250, null=True)),
                ('status_petition', models.CharField(default='P', max_length=1)),
                ('campus_petition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campus')),
                ('room_petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.event')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.module')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='roompetition_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.roompetition'),
        ),
    ]
