# Generated by Django 3.2 on 2021-12-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_auto_20211202_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_petition', models.CharField(default='', max_length=50)),
                ('email_petition', models.CharField(default='', max_length=150)),
                ('nrc_petition', models.CharField(blank=True, default='', max_length=10)),
                ('cant_pc_petition', models.IntegerField(default='')),
                ('day_start_petition', models.DateField(null=True)),
                ('day_finish_petition', models.DateField(null=True)),
                ('memo_petition', models.CharField(default='', max_length=250, null=True)),
                ('status_petition', models.CharField(blank=True, choices=[('P', 'Pendiente'), ('A', 'Aceptado'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('campus_petition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campus')),
                ('laboratory_petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_module', models.CharField(default='', max_length=50)),
                ('name_module', models.CharField(default='', max_length=50)),
                ('start_module', models.TimeField(null=True)),
                ('finish_module', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='modulepetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_mp', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=50)),
                ('labpetition_mp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.labpetition')),
                ('module_mp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.module')),
            ],
        ),
    ]
