# Generated by Django 3.2 on 2021-12-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpetition',
            name='recurrence',
            field=models.CharField(choices=[('01', 'Diario'), ('07', 'Semanal'), ('28', 'Mensual')], default='01', max_length=2),
        ),
    ]
