# Generated by Django 3.2 on 2021-12-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='resume_module',
            field=models.CharField(default='', max_length=50),
        ),
    ]
